-- create database ProyectoCineMYSQL;

CREATE TABLE CATEGORIA(
	
	id VARCHAR(20),
	nombre VARCHAR(40),
	
	CONSTRAINT PK_CATEGORIA PRIMARY KEY (id)

);


CREATE TABLE DIRECTOR
(

	dni VARCHAR(10),
	nombre VARCHAR(40),
	nacionalidad VARCHAR(30),
	edad INT(3),
	
	CONSTRAINT PK_DIRECTOR PRIMARY KEY (dni)
);


CREATE TABLE ACTOR
(

	dni VARCHAR(10),
	nombre VARCHAR(40),
	nacionalidad VARCHAR(30),
	edad INT(3),
	
	CONSTRAINT PK_ACTOR PRIMARY KEY(dni)

);

CREATE TABLE USUARIO
(

	id VARCHAR(20),
	fecha_reg DATE,
	email VARCHAR(40),

	CONSTRAINT PK_USUARIO PRIMARY KEY (id)
	
);


CREATE TABLE PAIS
(

	id VARCHAR(20),
	nombre VARCHAR(40),
	idioma VARCHAR(20),
	
	CONSTRAINT PK_PAIS PRIMARY KEY(id)

);


CREATE TABLE SUSCRIPCION
(
	
	id VARCHAR(20),
	tipo VARCHAR(20),
	precio INT(3),
	id_usu VARCHAR(20),
	
	CONSTRAINT PK_SUSCRIPCION PRIMARY KEY(id),
	CONSTRAINT FK1_SUSCRIPCION FOREIGN KEY(id_usu) REFERENCES USUARIO(id)

);

CREATE TABLE PERFIL
(

	id VARCHAR(20),
	nombre VARCHAR(40),
	pin VARCHAR(10),
	edad INT(3),
	id_usu VARCHAR(20),
	
	CONSTRAINT PK_PERFIL PRIMARY KEY(id),
	CONSTRAINT FK1_PERFIL FOREIGN KEY(id_usu) REFERENCES USUARIO(id)
);

CREATE TABLE CONTENIDO
(

	id VARCHAR(20),
	titulo VARCHAR(40),
	sinopsis VARCHAR(120),
	anio INT(4),
	tipo VARCHAR (20),
	dni_dire VARCHAR(10),
	
	CONSTRAINT PK_CONTENIDO PRIMARY KEY(id),
	CONSTRAINT FK1_CONTENIDO FOREIGN KEY(dni_dire) REFERENCES DIRECTOR(dni)
);

CREATE TABLE GUARDAN
(

	id_contenido VARCHAR(20),
	id_perfiles VARCHAR(20),
	
	CONSTRAINT PK_GUARDAN PRIMARY KEY(id_contenido,id_perfiles),
	CONSTRAINT FK1_GUARDAN FOREIGN KEY(id_contenido) REFERENCES CONTENIDO(id),
	CONSTRAINT FK2_GUARDAN FOREIGN KEY(id_perfiles) REFERENCES PERFIL(id)
);

CREATE TABLE ACTUA
(

	id_contenido VARCHAR(20),
	dni_actores VARCHAR(10),
	
	CONSTRAINT PK_ACTUA PRIMARY KEY (id_contenido, dni_actores),
	CONSTRAINT FK1_ACTUA FOREIGN KEY (id_contenido) REFERENCES CONTENIDO(id)
);

CREATE TABLE VISUALIZA
(
	id_contenido VARCHAR(20),
	id_paises VARCHAR(20),
	
	CONSTRAINT PK_VISUALIZA PRIMARY KEY(id_contenido,id_paises),
	CONSTRAINT FK1_VISUALIZA FOREIGN KEY(id_contenido) REFERENCES CONTENIDO(id),
	CONSTRAINT FK2_VISUALIZA FOREIGN KEY(id_paises) REFERENCES PAIS(id)	
	

);

CREATE TABLE PERTENECE
(

	id_contenido VARCHAR(20),
	id_categorias VARCHAR(20),
	
	CONSTRAINT PK_PERTENECE PRIMARY KEY(id_contenido, id_categorias),
	CONSTRAINT FK1_PERTENECE FOREIGN KEY(id_contenido) REFERENCES CONTENIDO(id),
	CONSTRAINT FK2_PERTENECE FOREIGN KEY(id_categorias) REFERENCES CATEGORIA(id)
);