--ALTER SESSION SET "_oracle_Script"=TRUE;
--CREATE USER ProyectoCine IDENTIFIED BY ProyectoCine;
--GRANT CONNECT,RESOURCE,DBA TO ProyectoCine;

 


CREATE TABLE CATEGORIA(
	
	id VARCHAR2(20),
	nombre VARCHAR2(40),
	
	CONSTRAINT PK_CATEGORIA PRIMARY KEY (id)

);


CREATE TABLE DIRECTOR
(

	dni VARCHAR2(10),
	nombre VARCHAR2(40),
	nacionalidad VARCHAR2(30),
	edad NUMBER(3),
	
	CONSTRAINT PK_DIRECTOR PRIMARY KEY (dni)
);


CREATE TABLE ACTOR
(

	dni VARCHAR2(10),
	nombre VARCHAR2(40),
	nacionalidad VARCHAR2(30),
	edad NUMBER(3),
	
	CONSTRAINT PK_ACTOR PRIMARY KEY(dni)

);

CREATE TABLE USUARIO
(

	id VARCHAR2(20),
	fecha_reg DATE,
	email VARCHAR2(40),

	CONSTRAINT PK_USUARIO PRIMARY KEY (id)
	
);


CREATE TABLE PAIS
(

	id VARCHAR2(20),
	nombre VARCHAR2(40),
	idioma VARCHAR2(20),
	
	CONSTRAINT PK_PAIS PRIMARY KEY(id)

);


CREATE TABLE SUSCRIPCION
(
	
	id VARCHAR2(20),
	tipo VARCHAR2(20),
	precio NUMBER(3),
	id_usu VARCHAR2(20),
	
	CONSTRAINT PK_SUSCRIPCION PRIMARY KEY(id),
	CONSTRAINT FK1_SUSCRIPCION FOREIGN KEY(id_usu) REFERENCES USUARIO(id)

);

CREATE TABLE PERFIL
(

	id VARCHAR2(20),
	nombre VARCHAR2(40),
	pin VARCHAR2(10),
	edad NUMBER(3),
	id_usu VARCHAR2(20),
	
	CONSTRAINT PK_PERFIL PRIMARY KEY(id),
	CONSTRAINT FK1_PERFIL FOREIGN KEY(id_usu) REFERENCES USUARIO(id)
);

CREATE TABLE CONTENIDO
(

	id VARCHAR2(20),
	titulo VARCHAR2(40),
	sinopsis VARCHAR2(120),
	anio NUMBER(4),
	tipo VARCHAR2(20),
	dni_dire VARCHAR2(10),
	
	CONSTRAINT PK_CONTENIDO PRIMARY KEY(id),
	CONSTRAINT FK1_CONTENIDO FOREIGN KEY(dni_dire) REFERENCES DIRECTOR(dni)
);

CREATE TABLE GUARDAN
(

	id_contenido VARCHAR2(20),
	id_perfiles VARCHAR2(20),
	
	CONSTRAINT PK_GUARDAN PRIMARY KEY(id_contenido,id_perfiles),
	CONSTRAINT FK1_GUARDAN FOREIGN KEY(id_contenido) REFERENCES CONTENIDO(id),
	CONSTRAINT FK2_GUARDAN FOREIGN KEY(id_perfiles) REFERENCES PERFILES(id)
);

CREATE TABLE ACTUA
(

	id_contenido VARCHAR2(20),
	dni_actores VARCHAR2(10),
	
	CONSTRAINT PK_ACTUA PRIMARY KEY (id_contenido, dni_actores),
	CONSTRAINT FK1_ACTUA FOREIGN KEY (id_contenido) REFERENCES CONTENIDO(id)
);

CREATE TABLE VISUALIZA
(
	id_contenido VARCHAR2(20),
	id_paises VARCHAR2(20),
	
	CONSTRAINT PK_VISUALIZA PRIMARY KEY(id_contenido,id_paises),
	CONSTRAINT FK1_VISUALIZA FOREIGN KEY(id_contenido) REFERENCES CONTENIDO(id),
	CONSTRAINT FK2_VISUALIZA FOREIGN KEY(id_paises) REFERENCES PAIS(id)	
	

);

CREATE TABLE PERTENECE
(

	id_contenido VARCHAR2(20),
	id_categorias VARCHAR2(20),
	
	CONSTRAINT PK_PERTENECE PRIMARY KEY(id_contenido, id_categorias),
	CONSTRAINT FK1_PERTENECE FOREIGN KEY(id_contenido) REFERENCES CONTENIDO(id),
	CONSTRAINT FK2_PERTENECE FOREIGN KEY(id_categorias) REFERENCES CATEGORIA(id)
);




